### ISSUE TITLE
testCasePid - automatic creation/retrieval

### ISSUE THREAD

**Issue by ghost** [samaysimantbarik/QTestHelper#1]
Firstly: great solution! Very helpful to have this handler for the api and such a simple implementation to get operational. Thank you. 

When I am using `executeTestRun` the command requires `testCasePid` however our users will add and remove tests all the time and logging into QTest to add a test case just to get the ID feels counterintuitive. 

Additionally your documentation (and code) refer to the `TC-57` style is but it doesn’t work and the id from the url for the test case does. 

Is it possible to use the supplied `description`, aka Test Name, to retrieve an existing test and it’s ID, or if not existing, create a test case and retrieve the ID, and use that in the execute TestRun instead? That would simplify the test management a lot.

**Comment by samaysimantbarik** [comment]
Hi @2erix ,

Glad that you liked the solution. Thanks, heaps.

1) TC-57 style: Do you mean the below style doesn't work for you? 
![image](https://user-images.githubusercontent.com/44022711/200758853-db998956-97db-4805-b91d-b5215c948d04.png)

In the below implementation, we are passing the TC in the test case description
![image](https://user-images.githubusercontent.com/44022711/200759149-180dfb86-1db1-4cdd-aaf8-777c548cac65.png)

2) Retrieving/Creating tests based on the description: It can be done but will result in flaky behaviour as the description is not unique in QTest. You may have the same tests under different folders/suites with the same name. That will result in incorrect reporting.

**Comment by ghost** [comment]
Thanks for the quick response!

1. Yep, didn’t work for me but passing the url ID for the test case did. Instrumenting each of the tests to have the ID with @TC-66 was something we want to avoid. Extra work! 
Also I don’t believe I noticed that in your docs so I can try that out. But I assume that is your implementation in your test project? At the moment I am just hard coding the code for the ids so we can get it operational, then we will address the implementation pattern for users. 

2. For us that is the desired outcome. We also battle actively against users re-using test names so that is a great outcome for us. They will be forced to make test names unique 😂 

Solution wise I would propose that you log counts higher than one for a test case name as a warning and use the first matched item.

**Comment by samaysimantbarik** [comment]
Hi @2erix ,

The precursor is that one already has the functional tests maintained in the QTest repository.
Then they automate some of the tests and report the results back to Test Execution.

Battling against re-using the names might be advisory but can never be mandated. Moreover, let's say you have 1000 tests already sitting in the repo and you want to add a new test; it would be cumbersome to skim through the names of the thousand tests to ensure you aren't accidentally creating duplicates.

However, I will add this new feature request to the list. Instead of modifying the behaviour of the existing method, will create another method to update tests based on the description. Shall keep you posted.

Thanks

**Comment by ghost** [comment]
Thanks! Do you have a public feature list?

Also I had a quick look at the API and the only way they have allowed to find the test by name would be using the search API so it will be a lot slower than what you have implemented and it returns both the TC and the TR items that have the test name. Additionally there could be partial matches that would make this a non-trivial exercise. 

Thanks for looking at it though. Keep up the good work.

**Comment by ghost** [comment]
I had a go, and I have it working but you will want to refactor the solution to meet your project flavour. 

I cannot supply the code as text because our laptops are locked down and unable to post here so I am using my phone 🤣  but I have attached the two functions as images I built to deal with the issue. 

Solution finds test id (not pid) by testname and if not found creates a new test and supplies the new test is back to the main method. Main method does the run as per your readme. 

Doing a run on the release id for the new test forms the linking so there are no extra api calls needed for linking the test to the release. 

Downside is that you do need to manually add the release id to the spec file/s so the test will be written correctly and the new tests get dumped by the api into a basic folder in test design, so manually sorting that in once in a while would be a good idea. 

You also may want to add more detail to the test than I have. 

Hopefully these help you get a solve quickly. 

![image](https://user-images.githubusercontent.com/10412078/201055720-32fb9639-8358-4856-9a5f-fe65a085f58c.jpg)

![90BACA36-3C93-4B3B-AC21-16D1528B5BA4](https://user-images.githubusercontent.com/10412078/201055382-d75c6cb2-1d17-47c1-8a01-6925df947f8f.jpeg)
![D52541DA-A2F6-4DFF-B10A-5388A40271C3](https://user-images.githubusercontent.com/10412078/201055419-7ad7d761-7c88-4f67-a3c8-bc092ee69a0a.jpeg)

**Comment by samaysimantbarik** [comment]
Hi @2erix ,

Thanks for your suggestions.
I am currently working on this feature with a slightly different approach. Should be there shortly.
Cheers

**Comment by samaysimantbarik** [comment]
Hi @2erix ,

Please give this a try:  https://www.npmjs.com/package/qtest_integration/v/1.2.1
